apiVersion: apps/v1
kind: Deployment
metadata:
  name: nastyretard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nastyretard
  template:
    metadata:
      labels:
        app: nastyretard
    spec:
      containers:
        - name: nastyretard
          image: nastyretard
          imagePullPolicy: Always
      restartPolicy: Always